# Generated by Django 4.0.4 on 2022-04-14 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chaves',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chavePublica', models.CharField(max_length=100000, verbose_name='Chave Pública')),
                ('chavePrivada', models.CharField(max_length=100000, verbose_name='Chave Privada')),
            ],
        ),
    ]
