# Generated by Django 4.0.4 on 2022-04-15 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_chaves_assinatura'),
    ]

    operations = [
        migrations.AddField(
            model_name='chaves',
            name='sha',
            field=models.CharField(default=None, max_length=10, verbose_name='Chave Pública'),
            preserve_default=False,
        ),
    ]
